import bannerImg from '../../assets/projectDetails/oilandgasmain.jpeg';
import cardImg from '../../assets/projectDetails/card.png';
import pks from '../../assets/projectDetails/smalloilandgas.jpeg';
import rmbanner from '../../assets/projectDetails/rmbanner.png';
import rm from '../../assets/projectDetails/rm.webp';
import projectImg1 from '../../assets/projectDetails/secondimages.jpeg';
import projectImg2 from '../../assets/projectDetails/oilandgasthirdimage.jpeg';
import projectImg3 from '../../assets/projectDetails/waste3.jpeg';
import projectImg4 from '../../assets/projectDetails/waste4.jpeg';
// import projectImg5 from '../../assets/projectDetails/';
// import projectImg6 from '../../assets/projectDetails/';
import projectImgf from '../../assets/projectDetails/warehouse4.jpg';
import projectImgq from '../../assets/projectDetails/warehouse2.jpg';
import projectImgflog from '../../assets/projectDetails/log3.webp';
import projectImgqlog from '../../assets/projectDetails/log4.webp';
import hrbg from '../../assets/projectDetails/waste22.jpeg';
import hrsmall from '../../assets/projectDetails/waste2.webp';
import logistic from '../../assets/projectDetails/warehouse1.jpeg';
import sslog from '../../assets/projectDetails/warehouse2.jpg';
import ss from '../../assets/projectDetails/warehouse3.jpeg';
import ssbg from '../../assets/projectDetails/warehouse1.jpeg';
import oop from '../../assets/projectDetails/oop.jfif';
import oopbg from '../../assets/projectDetails/oopbg.jpg';

const fakeData = [
  {
    id: 1,
    banner: bannerImg,
    title: 'Project Details',
    heading: 'Oil and Gas Services - Drilling Services',
    subHeading:
      'Save Energy needed to access oil reserves in a remote location with difficult terrain and limited infrastructure',
    card: {
      client: 'Save Energy',
      categories: 'Installation',
      date: '23 June 2017',
      tags: 'Transportation and storage ',
      img: pks,
    },

    para1:
      'Solution: Our team provided a full suite of drilling services, including drilling rig setup, directional drilling, and well completion. We also managed transportation logistics for equipment and personnel to the remote site. To overcome the challenge of the remote location and difficult terrain, we utilized advanced drilling technologies such as extended reach drilling and managed pressure drilling, which allowed us to drill deeper and more efficiently while minimizing the risk of well control issues.',
    para2:
      ' Our experienced personnel also worked closely with the client to ensure that safety protocols were followed and environmental impact was minimized.',
    para3:
      'The client was satisfied with the quality of work and our ability to overcome the challenges posed by the remote location, and has since engaged us for additional drilling projects in the region.',
    summary:
      'Results: By utilizing advanced drilling technologies and experienced personnel, we were able to successfully complete the drilling project on time and within budget, helping XYZ Energy to access valuable oil reserves. The project was completed with zero lost time incidents, demonstrating our commitment to safety and environmental responsibility',
    img1: projectImg1,
    img2: projectImg2,
  },
  {
    id: 2,
    banner: hrbg,
    title: 'Project Details',
    heading: 'Waste Management Services - Recycling Services',
    subHeading:
      'ABC Corporation was generating a significant amount of waste materials and wanted to reduce their environmental impact by increasing recycling efforts.',
    card: {
      client: 'ABC Corporation',
      categories: 'Waste management',
      date: '23 September 2020',
      tags: 'Waste collection ',
      img: hrsmall,
    },
    para1:
      'Solution: Our team provided recycling services for a variety of materials generated by ABC Corporation, including paper, cardboard, plastics, and metals. We worked closely with the company to implement a comprehensive recycling program, including employee education and training, bin placement and signage, and regular waste audits to track progress. ',
    para2:
      'Our team also provided customized waste management solutions to meet the specific needs of the client, such as waste reduction initiatives and waste-to-energy conversion options.',
    para3:
      'Results: By increasing their recycling efforts, ABC Corporation was able to significantly reduce their waste sent to landfills, resulting in cost savings and improved environmental sustainability.',
    summary:
      'The company was also able to achieve their sustainability goals and demonstrate their commitment to environmental responsibility to stakeholders. Our team continues to work with ABC Corporation to monitor and improve their waste management practices, and the client has reported high levels of satisfaction with our services.',
    img1: projectImg3,
    img2: projectImg4,
  },
  {
    id: 3,
    banner: logistic,
    title: 'Project Details',
    heading: 'Logistics Services - Supply Chain Management',
    subHeading:
      'Cosmas Retailer needed to improve their inventory management processes to better track and manage their stock levels',
    card: {
      client: 'Brenda parts Manufacturing',
      categories: 'Logistics',
      date: '19 December 2016',
      tags: 'Logistics services',
      img: sslog,
    },
    para1:
      'Solution: Our team provided comprehensive supply chain management services, including sourcing materials, managing suppliers, coordinating transportation and logistics, and overseeing inventory management. We worked closely with Brenda foods Manufacturing to develop a customized supply chain strategy that optimized costs and delivery times while maintaining quality standards',
    para2:
      'Our team also provided advanced data analytics and forecasting capabilities to help the client make informed decisions and anticipate potential supply chain disruptions.',
    para3:
      "Results: By implementing our supply chain management solutions, Brenda foods Manufacturing was able to reduce costs and improve delivery times, resulting in increased customer satisfaction and improved profitability. Our team's ability to anticipate and respond to supply chain disruptions helped to mitigate risks and maintain business continuity.",
    summary:
      'The client reported high levels of satisfaction with our services, and has since engaged us for additional supply chain management projects.',
    img1: projectImgqlog,
    img2: projectImgflog,
  },
  {
    id: 4,
    banner: oopbg,
    title: 'Project Details',
    heading: 'Oil and Gas Services - Drilling Services',
    subHeading:
      'Zigma Energy needed to access oil reserves in a remote location with difficult terrain and limited infrastructure..',
    card: {
      client: ' Zigma Energy',
      categories: 'oil and gas',
      date: '2 July 2021',
      tags: 'System, Banking, Design',
      img: oop,
    },
    para1:
      'Systems development is an important part of solving a business problem. It is important to understand the problem that is being solved and have ways in which the solution will follow the principles and procedures for the solution process. If there is no due diligence in the development of an information system that will solve a given problem, it will mean that there will be problems with the alignment with the business.',
    para2:
      'The solution will not align well with the system and there will be issues and problems that will arise with the development of the system. There is a need to ensure that there is better understanding of the requirements of the system and the solution it will offer to the business',
    para3:
      'This paper will focus on software design analysis for a banking institution that will manage the banking processes. It is designed to show the ways in which the banking process will be carried out in the design of computer-based system. The paper will then focus on the development and assessment of the banking system',
    summary:
      'In the project, there are objects and classes which will be integrated in the design of the system. Objects are the basic units from which object oriented programming is based. There are many issues and components that are used in the development of object oriented programming. Objects are important components in programing because they allow the programmers to relate real-world objects into programing environment.',
    // img1: projectImg5,
    // img2: projectImg6,
  },
  {
    id: 5,
    banner: rmbanner,
    title: 'Project Details',
    heading: 'One of our product that makes us stand out',
    subHeading:
      'Computers, Software, Windows, Internet, Workplace, Laptop, Mobility, Office',
    card: {
      client: 'Constance Robert',
      categories: 'Software',
      date: '1 April 2020',
      tags: 'Windows, Internet, Workplace',
      img: rm,
    },
    para1:
      'Widget Wonders require wireless internet connection for access of company resources by sales department staff. Software applications such as word processors, spreadsheet and internet will be required by manufacturing department. The graphics and computer aided design (CAD) software are also needed by research and development department while MIS department will require extra processor and memory to support administrative tasks. Other requirements include the most appropriate operating system that can support all the departments and system security software.',
    para2:
      'Microsoft office software will be needed to provide word processing, excel spreadsheet for manufacturing department. Microsoft office will also provide ms outlook for internet access within manufacturing department. The same Microsoft office will provide PowerPoint presentation software for the sales department so that they can make presentations at sales meeting and conferences (Collins 2013)',
    para3:
      'Because of their high number, the sales department staff will need laptop computers with Bluetooth and Wi-Fi software features to enable every employee to access wireless network. The laptops will also enhance their mobility',
    summary:
      'The recommendations given above are based on the minimum required specifications. The recommendations will also last for three years given that new software technology upgrade do come to the market within the time frame of 2 to 3 years. The company will therefore be in a position to use the recommended software until the fresh ones are introduced to the market in approximately three years time after when it can decide to go for new purchase or upgrade. The change of technology will call for the company to embrace for change as accompany which applies advanced technologies to enhance its competitive position',
    img1: projectImg1,
    img2: projectImg2,
  },
  {
    id: 6,
    banner: ssbg,
    title: 'Project Details',
    heading: 'Warehousing Services - Inventory Management',
    subHeading:
      'Cosmas Retailer needed to improve their inventory management processes to better track and manage their stock levels',
    card: {
      client: 'Cosmas Retailer',
      categories: 'Warehousing',
      date: '19 December 2016',
      tags: 'Warehousing services',
      img: ss,
    },
    para1:
      'Solution: Our team provided comprehensive inventory management services, including stock taking, inventory tracking, and order fulfillment. We worked closely with XYZ Retailer to implement a customized inventory management system that utilized advanced technologies such as barcoding and RFID tracking to improve accuracy and efficiency. ',
    para2:
      'Our team also provided data analytics and forecasting capabilities to help the client make informed decisions and optimize their inventory levels.',
    para3:
      "Results: By implementing our inventory management solutions, XYZ Retailer was able to improve their stock accuracy, reduce inventory carrying costs, and improve order fulfillment times. Our team's data analytics and forecasting capabilities helped the client to anticipate demand and make informed decisions about inventory levels, resulting in improved profitability.",
    summary:
      'The client was satisfied with the quality of work and our ability to improve their inventory management processes, and has engaged us for additional warehousing and logistics projects.',
    img1: projectImgq,
    img2: projectImgf,
  },
];
export default fakeData;